"""
Pydantic models for telemetry payloads.

Mirrors the SensorReading interface emitted by the ingestion-service
on the ``telemetry:inserted`` Redis Pub/Sub channel.
"""

from datetime import datetime

from pydantic import BaseModel, Field


class TelemetryReading(BaseModel):
    """
    Flattened sensor reading as published by the ingestion-service.

    Field names use camelCase to match the JSON produced by the TypeScript side.
    """

    device_id: str = Field(alias="deviceId")
    timestamp: datetime
    soil_temperature: float = Field(alias="soilTemperature")
    soil_humidity: float = Field(alias="soilHumidity")
    env_temperature: float = Field(alias="envTemperature")
    env_humidity: float = Field(alias="envHumidity")
    light_lux: float = Field(alias="lightLux")
    soil_ph: float | None = Field(default=None, alias="soilPh")
    soil_conductivity: float | None = Field(default=None, alias="soilConductivity")

    model_config = {"populate_by_name": True}


# ---------------------------------------------------------------------------
# Insight endpoint schemas
# ---------------------------------------------------------------------------
class InsightRequest(BaseModel):
    """Payload for POST /api/v1/insights."""

    query: str = Field(
        ...,
        min_length=1,
        description="The user's natural language question about the greenhouse.",
    )
    lat: float | None = Field(default=-6.920207, description="Latitude for weather forecast")
    lon: float | None = Field(default=107.772969, description="Longitude for weather forecast")


class InsightResponse(BaseModel):
    """Response from POST /api/v1/insights."""

    answer: str = Field(
        ...,
        description="Natural language insight generated by the AI.",
    )
    status: str = Field(
        default="ok",
        description="'ok' or 'error'.",
    )

class ChatMessagePayload(BaseModel):
    role: str
    content: str

class ChatRequest(BaseModel):
    messages: list[ChatMessagePayload]
    session_id: str | None = None

class ChatResponse(BaseModel):
    answer: str
    status: str = "ok"
    session_id: str | None = None

